name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: ./.code
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: './.code/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm i
      - name: Create pages
        run: pnpm run publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
